-- Criação da tabela 'leads' para armazenar contatos do site
create table if not exists leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text,
  whatsapp text,
  email text,
  service_name text, -- Nome do serviço (se agendamento)
  appointment_date date, -- Data agendada (se houver)
  appointment_time text, -- Horário agendado (se houver)
  professional_id bigint references professionals(id), -- FK para profissional (se houver tabela professionals)
  mensagem_interesse text, -- Mensagem se for apenas contato
  status_kanban text default 'novo', -- novo, agendado, concluido, cancelado
  admin_notes text -- Notas internas do admin
);

-- Políticas de Segurança (RLS) - Opcional para começar, mas recomendado
-- Habilitar RLS
alter table leads enable row level security;

-- Permitir leitura para todos (ou restrito a authenticated se tiver auth)
create policy "Enable read access for all users" on leads for select using (true);

-- Permitir inserção para todos (público do site)
create policy "Enable insert access for all users" on leads for insert with check (true);

-- Permitir atualização apenas para admins (se tiver auth configurado), por enquanto liberado
create policy "Enable update for all users" on leads for update using (true);
