-- SCRIPT DE RESTAURAÇÃO: IDs FIXOS E DADOS VISÍVEIS
-- Vamos forçar os IDs para garantir que os leads apareçam.

-- 1. Reset Total
drop table if exists leads;
drop table if exists professionals;

-- 2. Recriação das Tabelas
create table professionals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  specialties text[], 
  photo_url text,
  active boolean default true
);

create table leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text,
  whatsapp text,
  email text,
  service_name text,
  appointment_date date,
  appointment_time text,
  professional_id bigint references professionals(id),
  mensagem_interesse text,
  status_kanban text default 'novo', 
  admin_notes text
);

-- 3. Políticas de Segurança (Liberar Geral)
alter table professionals enable row level security;
create policy "public_pros_policy" on professionals for all using (true) with check (true);

alter table leads enable row level security;
create policy "public_leads_policy" on leads for all using (true) with check (true);

-- 4. INSERIR PROFISSIONAIS COM IDs GARANTIDOS (1, 2, 3)
insert into professionals (id, name, specialties, photo_url) 
overriding system value 
values 
(1, 'Massoterapeuta (Vestido Azul)', 
 ARRAY['Massagem Relaxante', 'Ventosa com relaxante', 'Tailandesa', 'Vivência Delirium', 'Nuru', 'Massagem relaxante especial', 'Terapia Tântrica'], 
 '/assets/pros/vestido_azul.jpg'),

(2, 'Massoterapeuta (Praia)', 
 ARRAY['Massagem Relaxante', 'Ventosa com relaxante', 'Tailandesa', 'Vivência Delirium', 'Nuru', 'Massagem relaxante especial', 'Terapia Tântrica'], 
 '/assets/pros/praia.jpg'),

(3, 'Massoterapeuta (Sol)', 
 ARRAY['Massagem Relaxante', 'Ventosa com relaxante', 'Tailandesa', 'Vivência Delirium', 'Nuru', 'Massagem relaxante especial', 'Terapia Tântrica'], 
 '/assets/pros/tapando_sol.jpg');

-- 5. INSERIR LEADS DE TESTE (Vários para garantir visibilidade)
insert into leads (created_at, nome, whatsapp, service_name, status_kanban, professional_id) values
(now(), 'Cliente Novo (Teste)', '79999990001', 'Massagem Relaxante', 'novo', 1),
(now() - interval '2 days', 'Cliente Agendado', '79999990002', 'Tailandesa', 'agendado', 2),
(now() - interval '5 days', 'Cliente Concluído', '79999990003', 'Nuru', 'concluido', 3);
