-- ATENÇÃO: Isso vai APAGAR os dados atuais dessas tabelas para corrigir os tipos (UUID vs Integer)
drop table if exists leads;
drop table if exists professionals;

-- 1. Tabela de Profissionais
create table professionals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  specialties text[], 
  photo_url text,
  active boolean default true
);

-- 2. Tabela de Leads
create table leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text,
  whatsapp text,
  email text,
  service_name text,
  appointment_date date,
  appointment_time text,
  professional_id bigint references professionals(id),
  mensagem_interesse text,
  status_kanban text default 'novo', 
  admin_notes text
);

-- 3. Habilitar Segurança (RLS)
alter table professionals enable row level security;
create policy "all_pros" on professionals for all using (true) with check (true);

alter table leads enable row level security;
create policy "all_leads" on leads for all using (true) with check (true);

-- 4. Inserir Dados Fictícios
insert into professionals (name, specialties, photo_url) values 
('Dra. Ana Silva', ARRAY['Massagem Relaxante', 'Drenagem Linfática'], 'https://ui-avatars.com/api/?name=Ana+Silva&background=cffafe&color=0891b2'),
('Carlos Mendes', ARRAY['Shiatsu', 'Desportiva'], 'https://ui-avatars.com/api/?name=Carlos+Mendes&background=e0f2fe&color=0369a1');

insert into leads (created_at, nome, whatsapp, service_name, status_kanban, professional_id) values
(now(), 'João Pereira', '79999999999', 'Massagem Relaxante', 'novo', 1),
(now() - interval '1 day', 'Maria Souza', '79988888888', 'Drenagem Linfática', 'agendado', 1),
(now() - interval '2 days', 'Pedro Santos', '79977777777', 'Shiatsu', 'concluido', 2),
(now() - interval '3 days', 'Lucas Oliveira', '79966666666', 'Massagem Relaxante', 'novo', 1),
(now(), 'Amanda Rocha', '79922222222', 'Drenagem Linfática', 'novo', 1);
